### ISSUE TITLE
Support for cross-process events?

### ISSUE THREAD

**Issue by bmorton** [asaskevich/EventBus#11]
Is it possible to publish events in one golang program and subscribe to them from another?

**Comment by bennAH** [comment]
A potential solution would be to use rpc underneath a specialised event bus. Suggesting this because it will allow for handlers locally and on different networks.

The current design is my fault but I think this solution will help rid of the if statements for synchronous/asynchronous callbacks and allow for different specialised event buses.

Will hopefully look into it more, but in the meantime feel free to contribute ideas/code

**Comment by bennAH** [comment]
@asaskevich @bmorton 
Had time to experiment with using rpc to achieve this (available at my fork https://github.com/bennAH/EventBus). 

See: [Wiki] (https://github.com/bennAH/EventBus/wiki/%5BExperimental%5D-Support-for-cross-process-events)

What do you think?

**Comment by asaskevich** [comment]
Looks good and very functional, it can fully resolve this issue

**Comment by bennAH** [comment]
Thanks, will tidy this up a bit ahead to prepare for this being pulled in

**Comment by bennAH** [comment]
See https://github.com/asaskevich/EventBus/pull/15, this has been tidied up and committed. If there are any issues / critiques, feel free to fix or raise it.
